### PR TITLE
i126: general error handling

### LINKED ISSUE #126: Ensure errors are being passed along correctly
Examples of errors that should not show up as empty search results:
- Passenger server is not running
- Upstream service is returning an error (authentication error, 500 error, bad query error)

### Question
What information do we want to send to the Allsearch frontend when the API encounters an error? And how?

Right now, in development, if you try to search with an empty string, the response status is 400, but it also returns the json:

```json
{ error: "param is missing or the value is empty: query" }
```

However, in production, it also shows the response status 400, but it shows the generic PUL error page (see, e.g., https://allsearch-api.princeton.edu/search/catalog?query=). This may be an issue of needing to change behavior on the load balancer (in the Princeton Ansible NGINX config, probably something to do with the [errors.conf template](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/allsearch-api_prod.conf#L52)) if we do want to return more specific error messages.

### PR DESCRIPTION
**Pull request by sandbergja**
closes #126

### CODE REVIEW

File: spec/requests/dpul_spec.rb [hunk 1]
```diff
@@ -60,7 +60,7 @@
   end
 
   context 'without a search term' do
-    it 'returns a 422 unprocessable response' do
```
Comment (sandbergja) [inline spec/requests/dpul_spec.rb:63]: Just some cleanup: these tests had outdated descriptions

**Review by christinach — APPROVED** [review]
Thanks @sandbergja ! 
🍄 🍋
